### ISSUE TITLE
Checklist - Maltego Configuration File

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-FullContact#14]
Select "_Custom Selection_"
- [ ] Add "_Transform Hub Items_" -> "_Full Contact_"

Select "_Entities_"
- [ ] Add "_cmlh_" -> "_Link Analysis_"
- [ ] Add "_cmlh_" -> "_Error_"
- [ ] Add "_Groups_" -> "_Company_"
- [ ] ~Add "_Location_" -> "_Location Expanded_"~
- [ ] Add "_People_" -> "_Male_"
- [ ] Add "_People_" -> "_Female_"
- [ ] [maltego.affiliation.Twitter](https://docs.maltego.com/support/solutions/articles/15000018994-social-network#affiliation-twitter-0-2)

Select "_Transform Sets_"
- [ ] Add "_Deprecated by FullContact_"
- [ ] ~Add "_FullContact API v2_"~
- [ ] Add "_FullContact API v3_"

Select "_Machines_"
- [ ] ~Add "_FullContact Location_"~
- [ ] ~Add "_FullContact Name_"~

Select "_Icons_"
- [ ] Add "_cmlh_" -> "_Error_"
- [ ] Add ~"_cmlh_" -> "_FullContact_"~

**Comment by cmlh** [comment]
Fix #14

**Comment by cmlh** [comment]
Add "_Transform Sets_"

**Comment by cmlh** [comment]
Add [maltego.affiliation.Twitter](https://docs.maltego.com/support/solutions/articles/15000018994-social-network#affiliation-twitter-0-2)
