### ISSUE TITLE
Checklist - @FullContact Test Data

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-FullContact#15]
[Person](https://www.fullcontact.com/developer/docs/person/)
- [ ] bart@fullcontact.com
- [ ] a4cb1b07d68a3436a190e1559586ae3c (MD5 Hash)
- [ ] d4461112e12ab072ead550915dc11bcf9db974135f6ccc18799dbe1cb9516b81 (SHA-256)
- [ ] +13037170414
- [ ] @lorangb (Twitter)

[Company](
- [ ] fullcontact.com
- [ ] fullcontact (Company)

[E-mail Verification](https://www.fullcontact.com/developer/docs/email-verification/)
- [ ] matt@fullcontact.com
- [ ] bart@fullcontact.com
- [ ] travis@fullcontact.com
- [ ] bad-email@fullcontact.com

**Comment by cmlh** [comment]
FullContact API v2 is deprecated.
