### ISSUE TITLE
Checklist - FullContact Services Agreement

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-FullContact#16]
[@FullContact Services Agreement](https://www.fullcontact.com/services-agreement/)

- [x] From "_E-mail Address_" `maltego.EmailAddress` To [`E-mail Verification`](https://www.fullcontact.com/developer/docs/email-verification)

#### Person
- [x] From "_E-mail Address_" `maltego.EmailAddress` To [`Person`](https://www.fullcontact.com/developer/docs/person/)
- [x] From "_Hash_" `maltego.Hash` To [`Person`](https://www.fullcontact.com/developer/docs/person/)
- [x] From "_Telephone_" to [`Person`](https://www.fullcontact.com/developer/docs/person/#lookup-by-phone)
- [x] From "_Twitter_" to ['Person'](https://www.fullcontact.com/developer/docs/person/#lookup-by-twitter)

#### Name
- [x] From "_Phrase_" `maltego.Phrase` To [`Name Normalizer`](https://www.fullcontact.com/developer/docs/name/#name-normalization)
- [x] From "_Alias_" `maltego.Alias` To [`Name Deducer`](https://www.fullcontact.com/developer/docs/name/#name-deducer)
- [x] From "_E-mail Address_" `maltego.EmailAddress` To [`Name Deducer`](https://www.fullcontact.com/developer/docs/name/#name-deducer)
- [x] From "_Person_" `maltego.Person` To [`Name Parser`](https://www.fullcontact.com/developer/docs/name/#name-parser)
- [x] From "_Person_" `maltego.Person` To [`Name Stats`](https://www.fullcontact.com/developer/docs/name/#name-stats)

#### Company
- [x] From "_Domain_" `maltego.Domain` To [`Company Lookup`](https://www.fullcontact.com/developer/docs/company/#lookup-by-domain)
- [x] From "_Company_" `maltego.Company` To [`Company Lookup`](https://www.fullcontact.com/developer/docs/company/#lookup-by-company-name)

#### Location
- [x] From "_Phrase_" `maltego.Phrase` To [`Location Normalizer`](https://www.fullcontact.com/developer/docs/location/#location-normalization)
- [x] From "_Location_" `maltego.Location` To [`Location Enrichment`](https://www.fullcontact.com/developer/docs/location/#location-enrichment)

#### Account Statistics
From "_E-mail Address_" `maltego.EmailAddress` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)
From "_Location_" `maltego.Location` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/) 
From "_Domain_" `maltego.Domain` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)
From "_Person_" `maltego.Person` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)
From "_Phrase_" `maltego.Phrase` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)

**Comment by cmlh** [comment]
Fix #16
