### ISSUE TITLE
Checklist - Transform Metadata - FullContact API v2

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-FullContact#18]
- [ ] From "_E-mail Address_" `maltego.EmailAddress` To [`E-mail Verification`](https://www.fullcontact.com/developer/docs/email-verification)

#### Person
- [ ] From "_E-mail Address_" `maltego.EmailAddress` To [`Person`](https://www.fullcontact.com/developer/docs/person/)
- [ ] From "_Hash_" `maltego.Hash` To [`Person`](https://www.fullcontact.com/developer/docs/person/)
- [ ] From "_Telephone_" to [`Person`](https://www.fullcontact.com/developer/docs/person/#lookup-by-phone)
- [ ] From "_Twitter_" to ['Person'](https://www.fullcontact.com/developer/docs/person/#lookup-by-twitter)

#### Name
- [ ] From "_Phrase_" `maltego.Phrase` To [`Name Normalizer`](https://www.fullcontact.com/developer/docs/name/#name-normalization)
- [ ] From "_Alias_" `maltego.Alias` To [`Name Deducer`](https://www.fullcontact.com/developer/docs/name/#name-deducer)
- [ ] From "_E-mail Address_" `maltego.EmailAddress` To [`Name Deducer`](https://www.fullcontact.com/developer/docs/name/#name-deducer)
- [ ] From "_Person_" `maltego.Person` To [`Name Parser`](https://www.fullcontact.com/developer/docs/name/#name-parser)
- [ ] From "_Person_" `maltego.Person` To [`Name Stats`](https://www.fullcontact.com/developer/docs/name/#name-stats)

#### Company
- [ ] From "_Domain_" `maltego.Domain` To [`Company Lookup`](https://www.fullcontact.com/developer/docs/company/#lookup-by-domain)
- [ ] From "_Company_" `maltego.Company` To [`Company Lookup`](https://www.fullcontact.com/developer/docs/company/#lookup-by-company-name)

#### Location
- [ ] From "_Phrase_" `maltego.Phrase` To [`Location Normalizer`](https://www.fullcontact.com/developer/docs/location/#location-normalization)
- [ ] From "_Location_" `maltego.Location` To [`Location Enrichment`](https://www.fullcontact.com/developer/docs/location/#location-enrichment)

#### Account Statistics
From "_E-mail Address_" `maltego.EmailAddress` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)
From "_Location_" `maltego.Location` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/) 
From "_Domain_" `maltego.Domain` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)
From "_Person_" `maltego.Person` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)
From "_Phrase_" `maltego.Phrase` To [`Account Stats`](https://www.fullcontact.com/developer/docs/account-stats/)

**Comment by cmlh** [comment]
FullContact API v2 is deprecated.
