### ISSUE TITLE
Checklist - Transform Metadata - FullContact Enrich API

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-FullContact#22]
https://platform.fullcontact.com/docs/apis/enrich/introduction
- [x] To Person From Twitter
- [x] To Person From Telephone
- [x] To Person From Email
- [x] To Person From Hash of Email Address

https://platform.fullcontact.com/docs/apis/enrich/company-enrichment
- [x] To Company From Domain
- [x] To Company Name From [Company] Name

**Comment by cmlh** [comment]
Close #22
